# Location of database if already downloaded
database: "/home/bayraktar/PycharmProjects/reconstruct_plasmids/data/SRAmetadb.sqlite"
# NCBI taxon ID
#taxon_id: "543"
taxon_id: "67827"
# -i: download Illumina, -n download Nanopore, -p download Pacbio
download_platforms: "-i"