# Location of database if already downloaded
database: "../Data/SRAmetadb.sqlite"
# NCBI taxon ID
taxon_id: "'624'"
# -i: download Illumina, -n download Nanopore, -p download Pacbio
#download_platforms: "-i"